### ISSUE TITLE
Private projects don't appear in project list.

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#11]
I create a new private project (logged in as a system adminstrator). Project does not appear in my project list (http://cadasta-staging.spatialdevmo.com/project)

**Comment by joetsoi** [comment]
see https://github.com/ckan/ckan/issues/1239 and https://lists.okfn.org/pipermail/ckan-dev/2013-February/003873.html, private and draft datasets don't get added to the search index. They should appear in the organization search page.

**Comment by rgwozdz** [comment]
Hmm, ok.  Hopefully that will be in-line with current requirements, if not I'll have to re-open.
