### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#129]
on data source, survey sketch should  be changed to survey (or survey coordinates?)

landuse (residential/commercial) dropdown should be better aligned 

file upload description box should be bigger

choose file to upload button is off center

party date of birth label pops up for group

saturday date picker UI update

party list broadcast for update party

z index of field data and map layer toggle 

giant x for change org image button looks funny

filter and sort buttons are out of lines on resource tab

favicon and site title (switch in production.ini file on staging box)

**Comment by danielduhh** [comment]
Updated list:
favicon and site title (switch in production.ini file on staging box)
filter and sort buttons are out of lines on resource tab
giant x for change org image button looks funny
z index of field data and map layer toggle
Saturday date picker UI update

**Comment by thebigspoon** [comment]
most of these are done. creating separate issues for the things that are not done
