### ISSUE TITLE
upload image button

### ISSUE THREAD

**Issue by danielduhh** [Cadasta/ckanext-project#142]
The upload image button is actually above the blue div element
This is an old issue @sbindman has dealt with 

<img width="218" alt="screen shot 2015-11-24 at 12 30 39 pm" src="https://cloud.githubusercontent.com/assets/1947857/11379798/35531e06-92a7-11e5-9b9e-98ea3340906c.png">

**Comment by sbindman** [comment]
Button alignment has been fixed. CSS has not been fixed for hover state
