### ISSUE TITLE
The CKAN show organization endpoint should return a full list of org metadata

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#17]
Currently the ckan.logic.action.get.organization_show endpoint is only returning the title, id and name for a given package belonging to an organization. Previously it was also returning description and date modified.   Can this please be updated to include those fields.

See example: http://cadasta-staging.spatialdevmo.com/api/3/action/organization_show?id=american-red-cross&include_datasets=true

packages: [
{
title: "Haiti Assistance Program",
id: "49337dc1-00f2-4206-88c5-61139da6623f",
name: "haiti-assistance-program"
}
],

**Comment by joetsoi** [comment]
https://github.com/ckan/ckan/issues/2690 could you make sure you include include_datasets=true as a parameter to your calls to organization_show, this is for forwards compatibility purposes. (see linked issue)

**Comment by rgwozdz** [comment]
The issue persists even with include_datasets=true in the URL (see example is issue description).  Ideally, we would get each package's description and date modified, as well as its title, id, and name.  We were originally getting this information in the response to organization_show, but appears to be omittied in the latest update to this endpoint.

**Comment by joetsoi** [comment]
Have you tried with
https://github.com/okfn/ckanext-project/commit/17eb844da917169ed7571756ef1976502abf2d2a
pulled, that should include the description in the organistation show schema

The issue persists even with include_datasets=true in the URL (see example
is issue description). Ideally, we would get each package's description and
date modified, as well as its title, id, and name. We were originally
getting this information in the response to organization_show, but appears
to be omittied in the latest update to this endpoint.

—
Reply to this email directly or view it on GitHub
<https://github.com/Cadasta/ckanext-project/issues/17#issuecomment-149313575>
.

**Comment by thebigspoon** [comment]
@joetsoi: yep, this PR had it
