### ISSUE TITLE
Organization Overview page not correctly showing project count

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#18]
The organization overview page does not correctly show the number of projects associated with an organization

![screen shot 2015-10-16 at 2 47 51 pm](https://cloud.githubusercontent.com/assets/10539483/10554078/160ec35c-7415-11e5-87c4-e4547a2e9311.png)

**Comment by joetsoi** [comment]
https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/project/templates/organization/snippets/organization_item.html#L22

this snippet has been overridden to always show 0 projects

**Comment by thebigspoon** [comment]
merged. closing
