### ISSUE TITLE
How nuke the CKAN DB...?

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#20]
@joetsoi - is there any built in script for complete reseting a CKAN db?  We've accumulated a lot of garbage during the test phase...it would be nice to clear out orgs and project with true deletes (not archives).

**Comment by joetsoi** [comment]
`ckan db clean` should work for you, if not you can run `/usr/lib/ckan/default/bin/paster db clean -c /etc/ckan/default/production.ini` (this depends on the setup of the ckan viretual env)

**Comment by rgwozdz** [comment]
Where in the file structure should I run `ckan db clean`?  Tried it in a number of locations, and what I get is:

**Comment by rgwozdz** [comment]
Also tried `/usr/lib/ckan/default/bin/paster --plugin=ckan db clean -c /etc/ckan/default/development.ini`, database continue to have all data in it.

**Comment by thebigspoon** [comment]
this works
