### ISSUE TITLE
Get location dropdowns on new project page working.

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#21]
We need to figure out where to best store the GADM admin polygon data (CKAN , Cadasta DB, etc) and then make it available to the dropdowns on the "new Project" page.  Also need to determine best DB to stored the selected Admin locations (on project creation) - CKAN DB or Cadasta DB, and the alter server codes to ensure it is written to the data store.

**Comment by thebigspoon** [comment]
not needed anymore, closing
