### ISSUE TITLE
Connect CKAN "edit organization" event to "edit organization" endpoint in the Cadasta API

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#23]
Cadasta API endpoints forth coming.  https://github.com/okfn/ckanext-cadastaroles/issues/19 might help illuminate the path as it was the issue in which we connect CKAN create events to Cadasta API create events.

**Comment by rgwozdz** [comment]
Here is our Node endpoint: http://54.69.121.180:3000/docs/#api-Organizations-UpdateOrganization

**Comment by thebigspoon** [comment]
pushed to staging, works
