### ISSUE TITLE
Connect CKAN "edit project" event to "edit project" endpoint in the Cadasta API

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#24]
Cadasta API endpoints forth coming. okfn/ckanext-cadastaroles#19 might help illuminate the path as it was the issue in which we connect CKAN create events to Cadasta API create events.

Here is the Cadasta API endpoint http://54.69.121.180:3000/docs/#api-Projects-UpdateProject - the required ID, is the ID of the project in the Cadasta DB table.

**Comment by thebigspoon** [comment]
pushed to staging, works
