### ISSUE TITLE
Connect CKAN "delete organization" event to "delete organization" endpoint in the Cadasta API

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#26]
Cadasta API endpoints forth coming. okfn/ckanext-cadastaroles#19 might help illuminate the path as it was the issue in which we connect CKAN create events to Cadasta API create events.

Note that "delete" here really means archive.  CKAN doesn't really delete the org and we don't allow that in the Cadasta API either.

Here is the Cadasta API endpoint http://54.69.121.180:3000/docs/#api-Organizations-ArchiveOrganization - the required ID, is the ID of the org in the Cadasta DB table.

**Comment by thebigspoon** [comment]
release to staging and tested, closing
