### ISSUE TITLE
Alter CKAN Create Project trigger

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#31]
When an Project is created in the CKAN UI, the CKAN server code sends a request to the Cadasta API to create a Project in the Cadasta DB. The endpoint in the Cadasta API has changed (new POST parameters), so the request being sent from CKAN needs to be altered. See endpoint:

http://54.69.121.180:3000/docs/#api-Projects-PostProjects

**Comment by thebigspoon** [comment]
fixed in ac904b7416e2fd4dfb15856f20e89dc9da8b4e6b
