### ISSUE TITLE
Add Cadasta API Logging on DEBUG Level

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#33]

**Comment by rgwozdz** [comment]
I can do this...

**Comment by rgwozdz** [comment]
Cadasta API DEBUG logging with this commit 63ee3566c7de06e9839719b8383ffeb751d85d23

**Comment by thebigspoon** [comment]
nice. I was meaning for this to be in CKAN but it's good to have in two spots. Thansk @rgwozdz
