### ISSUE TITLE
Get user's role for a given project - without submitting user_id or organization_id

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#35]
See this thread: https://github.com/okfn/ckanext-cadastaroles/issues/20;

Currently the user_role_show CKAN endpoint requires user_id & organization_id.

We will not have the user_id when we execute this request - we were hoping use the session instead of having to submit the user_id.  I have noticed I can submit request to the API without the use of the API token, so the API must know the identity of the user already, right?

We may not always have the org id either.  Instead I was hoping the endpoint response could be organized as an array of organizations that the user is a member on.  each organization object in the array would include an array of projects that the organization is parent to.

**Comment by joetsoi** [comment]
We can get this in the request by using context['user'] instead of user_id

**Comment by rgwozdz** [comment]
Thanks Joe.  Would you provide some additional details?  here’s my jquery request…what would I change in the following url?

http://cadasta-staging.spatialdevmo.com/api/action/user_role_show?user_id=sarah&organization_id=habit

On Oct 21, 2015, at 4:08 PM, Joe Tsoi <notifications@github.com<mailto:notifications@github.com>> wrote:

We can get this in the request by using context['user'] instead of user_id

**Comment by joetsoi** [comment]
apologies, I wasn't clear [this line](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/cadastaroles/logic/action/get.py#L13) should be changed to `context['user']` and removing [this filter line](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/cadastaroles/logic/action/get.py#L22) should fix the user get role action

**Comment by rgwozdz** [comment]
Implemented with 343b170f8e5b9e270b80b5166d699e1afc90ef90.

**Comment by rgwozdz** [comment]
Hoping we can adjust this a little;  is there a way to add a property to the response to flag if the user is a sysadmin?

**Comment by rgwozdz** [comment]
@joetsoi - getting this error from the endpoint when a non-logged in user hits it:

Error - <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'id'
URL: http://localhost:5000/api/3/action/user_role_show
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py', line 389 in inner
  result = application(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/api.py', line 70 in __call__
  return base.BaseController.__call__(self, environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 337 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/api.py', line 201 in action
  result = function(context, request_data)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 416 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 502 in wrapper
  return action(context, data_dict)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 532 in wrapper
  return action(context, data_dict)
File '/usr/lib/ckan/default/src/ckanext-project/ckanext/cadastaroles/logic/action/get.py', line 17 in user_role_show
  .filter(model.Member.table_id == user.id)\
AttributeError: 'NoneType' object has no attribute 'id'


Can we adjust so that it sends back an empty array or some other message if the user is not logged in?

**Comment by thebigspoon** [comment]
@rgwozdz,
See PR #61 above. I ran into the same problem with a user that wasn't logged in. Are we using this information only to show/hide the edit link? Is it used anywhere else? I don't see it. Just wondering

**Comment by thebigspoon** [comment]
this seems to be fixed
