### ISSUE TITLE
Error on Save Project "...ckan organization id is not an integer.."

### ISSUE THREAD

**Issue by galenerickson** [Cadasta/ckanext-project#36]
Create Org.  Add title and desccription. Save.
![image](https://cloud.githubusercontent.com/assets/2992535/10651881/f861da42-7806-11e5-9101-8864e0540bbe.png)

**Comment by rgwozdz** [comment]
Yes, this is what I have been speaking about during scrum.  The databases are not synced and they both need to be wiped clean once we have them communicating properly.


On Oct 21, 2015, at 3:18 PM, galenerickson <notifications@github.com<mailto:notifications@github.com>> wrote:


Create Org. Add title and desccription. Save.
[image]<https://cloud.githubusercontent.com/assets/2992535/10651881/f861da42-7806-11e5-9101-8864e0540bbe.png>

**Comment by rgwozdz** [comment]
We'll leave this open until we wipe both DB's and start fresh.

**Comment by thebigspoon** [comment]
I'm pretty clear on why this is happening and I think so is @rgwozdz. It doens't happen when we get rid of the legacy data with the non integer ids. Let's close this
