### ISSUE TITLE
DefaultDatasetForm DELETE Hook

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#39]
Hey @joetsoi,
I'm looking for the place to create a hook or callback to handle Project and Organization deletes on the related cadasta resource. 

I see the DefaultDatasetForm has these [overrideable methods](https://github.com/ckan/ckan/blob/master/ckan/lib/plugins.py#L256-L263) for create, read and update. But I don't see delete.

Your help is much appreciated! Thanks!

**Comment by joetsoi** [comment]
Looks like it's a usecase no one has generally had to use. You have two choices 

[`IPackageController.after_delete`](http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IPackageController.after_delete) you are safe to use this as the commit will occur after the delete.

or

override the package_delete action in the extension and apply a schema there.

The after delete is probably how I'd go about doing it, originally I used the IPackageController.after_create/update for the api calls, but was saving the cadasta_id into a seperate field in ckan which causes issues as the IPackageController is bad at handling adding extras at that point and the id has already been assigned and flushed to the database, which is why the validator method was used to override the ids and make the call _before_ ckan created a project

**Comment by thebigspoon** [comment]
Thanks @joetsoi -- let me play with that

**Comment by thebigspoon** [comment]
Hey @joetsoi,
``IPackageController`` seems to have some odd behaviors after implementing it. It will enforces ``before_search``, ``before_view`` and ``after_search`` but does not ever call ``after_delete`` when an organization is deleted. 

I also notice that deleting an Organization with related packages blows up and the error seems to want me to override ``package_delete`` as far as I can see. So let me try doing it that way

```bash
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 337 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/group.py', line 649 in delete
  self._action('group_delete')(context, {'id': id})
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 416 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/delete.py', line 412 in organization_delete
  return _group_or_org_delete(context, data_dict, is_org=True)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/delete.py', line 366 in _group_or_org_delete
  _get_action('package_delete')(context, {'id': pkg.id})
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 416 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/delete.py', line 75 in package_delete
  item.delete(entity)
AttributeError: 'CadastaOrganization' object has no attribute 'delete'
```

**Comment by joetsoi** [comment]
Hum ,for organizations you should try and use the IOrganizationController.delete, so make [CadastaOrganization](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/project/plugin/organization.py#L25) have something like plugins.implements(IOrganizationController, inherit=True) and add the delete method there that calls the cadatsa_delete_organization-action.

at least that's looks like what ckan is attempting to call CadastaOrganization.delete

**Comment by thebigspoon** [comment]
I see. So there's conceptual bits that I'm missing about the difference between the Project and Organization plugin. 

You're saying for the Project Plugin cadasta calls will happen in ``IPackageController.after_delete``. For the Organization Plugin the override will happen at a different spot, namely, ``IOrganizationController.delete``.  Is that correct?

**Comment by joetsoi** [comment]
yes, if we change cadastaorganization to 'implement' the IOrganizationController interface.

somewhere in the `package_delete` action there is some code to loop over all IPackageController plugins and run that `after_delete` method

somewhere in the `organizaiton_delete` aciton there is some code to loop over all IOrganizationController plugins and run their delete method.

**Comment by thebigspoon** [comment]
got it, thanks @joetsoi
