### ISSUE TITLE
No User or Model Context for IOrganizationController.delete

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#46]
Hey @joetsoi,
The ``CadastaOrganization`` hook for ``delete`` currently works. But it will become problematic later when we need to pass the ``user`` onto cadasta. 

I'm noticing ``IOrganizationController.delete`` does not pass along ``user`` and ``model`` context information for the request. See the [code here](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/project/plugin/organization.py#L36-L39).

Is there anyway to get it?

**Comment by joetsoi** [comment]
hmm yeah, doesn't look like it does, it probably means having to override the action `organization_delete` instead and wrapping the core function.

**Comment by thebigspoon** [comment]
@joetsoi,
I implemented this. Do i have to verify that this user can call `organization_delete` before calling the cadasta api though? It seems like I should. 

Seems like `ckan.logic.action.delete._group_or_org_delete` checks the user's auth before setting the record to archived in the ckan database.

**Comment by joetsoi** [comment]
@thebigspoon, by the time you're in `orgnaization_delete` the auth function will have already been called. If you run the action `cadasta_organization_detele` using toolkit.get_action, it'll call the relevant auth function for you.

**Comment by thebigspoon** [comment]
this was pushed to staging and works
