### ISSUE TITLE
Server Error on New Project

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#47]
We logged in as user `orgadmin` and I try to visit the new project page http://cadasta-staging.spatialdevmo.com/project/new, I get "Server Error".

Ping me directly for orgadmin's password.

**Comment by thebigspoon** [comment]
@rgwozdz,
how was the user `orgaadmin` created?

**Comment by rgwozdz** [comment]
I self-registered thru the UI.   later As a sysadmin, I gave it OrgAdmin role on the SpatialDev organization.


On Oct 23, 2015, at 11:08 AM, sudobangbang <notifications@github.com<mailto:notifications@github.com>> wrote:


@rgwozdz<https://github.com/rgwozdz>,
how was the user orgaadmin created?

**Comment by thebigspoon** [comment]
@rgwozdz thanks,
I don't understand the authorization well enough to see the problem. But it's related to auth permissions so documenting here. Let me poke at it but I might need @joetsoi help. 

When the template is being rendered it's checking for ID(s) and it's not finding one. Again, this should come across as a rendered error and not a 500. Here's the traceback:

```bash
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return render_func()
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/lib/base.py', line 154 in render_template
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return render_jinja2(template_name, globs)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return template.render(**extra_vars)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py', line 894 in render
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return self.environment.handle_exception(exc_info, True)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckanext-project/ckanext/project/plugin/../templates/project/new_package_form.html', line 25 in top-level template code
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   {% block form_actions %}
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckanext-project/ckanext/project/plugin/../templates/project/new_package_form.html', line 36 in block "form_actions"
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   {% block delete_button %}
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckanext-project/ckanext/project/plugin/../templates/project/new_package_form.html', line 37 in block "delete_button"
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   {% if h.check_access('package_delete', {'id': data.id}) and not data.state == 'deleted' %}
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/lib/helpers.py', line 822 in check_access
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   logic.check_access(action, context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/__init__.py', line 283 in check_access
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/authz.py', line 175 in is_authorized
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return auth_function(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/delete.py', line 18 in package_delete
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return _auth_update.package_update(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/__init__.py', line 577 in wrapper
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return action(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/update.py', line 13 in package_update
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   package = logic_auth.get_package_object(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/__init__.py', line 34 in get_package_object
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return _get_object(context, data_dict, 'package', 'Package')
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File '/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/__init__.py', line 20 in _get_object
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   .format(class_name))
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] ValidationError: None - {'message': 'Missing id, can not get Package object'}

```

**Comment by joetsoi** [comment]
Hi I'm not at my desk but I'll take a look later

@rgwozdz <https://github.com/rgwozdz> thanks,
I don't understand the authorization well enough to see the problem. But
it's related to auth permissions so documenting here. Let me poke at it but
I might need @joetsoi <https://github.com/joetsoi> help.

When the template is being rendered it's checking for ID(s) and it's not
finding one. Again, this should come across as a rendered error and not a
500. Here's the traceback:

[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/templating.py',
line 249 in cached_template
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return render_func()
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/lib/base.py', line 154 in
render_template
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
render_jinja2(template_name, globs)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/lib/base.py', line 104 in
render_jinja2
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
template.render(**extra_vars)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py',
line 894 in render
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
self.environment.handle_exception(exc_info, True)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckanext-project/ckanext/project/plugin/../templates/project/new_package_form.html',
line 25 in top-level template code
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   {% block
form_actions %}
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckanext-project/ckanext/project/plugin/../templates/project/new_package_form.html',
line 36 in block "form_actions"
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   {% block
delete_button %}
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckanext-project/ckanext/project/plugin/../templates/project/new_package_form.html',
line 37 in block "delete_button"
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   {% if
h.check_access('package_delete', {'id': data.id}) and not data.state
== 'deleted' %}
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/lib/helpers.py', line 822
in check_access
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]
logic.check_access(action, context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/__init__.py', line
283 in check_access
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/authz.py', line 175 in
is_authorized
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
auth_function(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/delete.py',
line 18 in package_delete
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
_auth_update.package_update(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/__init__.py', line
577 in wrapper
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
action(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/update.py',
line 13 in package_update
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   package =
logic_auth.get_package_object(context, data_dict)
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/__init__.py',
line 34 in get_package_object
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   return
_get_object(context, data_dict, 'package', 'Package')
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139] File
'/home/ubuntu/ckan/lib/default/src/ckan/ckan/logic/auth/__init__.py',
line 20 in _get_object
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]   .format(class_name))
[Fri Oct 23 18:32:09 2015] [error] [client 174.21.38.139]
ValidationError: None - {'message': 'Missing id, can not get Package
object'}

—
Reply to this email directly or view it on GitHub
<https://github.com/Cadasta/ckanext-project/issues/47#issuecomment-150658013>
.

**Comment by thebigspoon** [comment]
@rgwozdz,
I seem to have lost my `sysadmin` command. Did we lose that when we merged cadastaroles plugin into this extension? Do you have access to it?

`paster sysadmin add USERNAME -c /etc/ckan/default/development.ini``

**Comment by thebigspoon** [comment]
@rgwozdz and @joetsoi,
Something has changed since this was a problem last, because it doesn't seem to be a problem anymore. The original `orgaadmin` user can now see thew new project page without a server error. 

I also went through the workflow of creating `orgaadmdin2` user through the UI and then on the staging server ran `paster sysadmin add orgaadmin2 -c /etc/ckan/default/development.ini` and that user can also see the new project page without an error.

@rgwozdz: can you run through this workflow one more time to see if it works?
Thanks

**Comment by thebigspoon** [comment]
Hey @joetsoi,
This problem is still around and very tricky. I'm gonna explain it below and hopefully that might jog some ideas on how to solve it:

## Problem
A new user, we'll refer to this person as `oadmin` below,  who is granted `OrgAdmin` privileges should have the ability to create, delete and update projects. 

When `oadmin` logs into CKAN and tries to immediately access the `/project/new` page they get a ServerError with the traceback mentioned two threads above. It seems the `data_dict` being passed has an `Undefined` id. 

If that same `orgadmin` goes to the `/organization/new` page they will get an `Unauthorized to create` error -- which is correct. After `orgadmin` tries this page and returns to the `/project/new` page they *won't* get the ServerError anymore but will be denied access to `/project/new` page -- which is not correct but better than a ServerError ;-)

Any good insights into this?

**Comment by joetsoi** [comment]
https://github.com/okfn/ckanext-project/commit/2482408721ea7cbd128cbde17854f50c82d288f6

So the problem occurs when rendering the delete button on `/project/new`, which makes no sense as a delete button should not be appearing in a 'Create new project'. There's no project id, so jinja just passes undefined and we end up with the server error.

So you need to change the form to check when you are on a 'New project' page, like the default one in ckan https://github.com/ckan/ckan/blob/master/ckan/templates/package/new_package_form.html#L26

I ended up having to set `form_action` as `action` was being overriden in the template snippet in ckanext-project.

**Comment by thebigspoon** [comment]
@rgwozdz,
I put in the change @joetsoi talked about and released to staging. Can you test this out and close this ticket if it's all good

I tested with user `orgadmin`

**Comment by thebigspoon** [comment]
fixed and released to staging
