### ISSUE TITLE
Turn off ckanext.cadasta.enforce_permissions in ckan.config

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#49]
It's my understanding that the config option `ckanext.cadasta.enforce_permissions` is checked [during cadasta api callls](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/cadastaroles/logic/action/api.py#L98-L100) to see if the user has the correct permissions to make said call.

We need to turn this off in staging ( the production.ini ) to make sure it works correctly.

@joetsoi: my assumptions above are correct, yes?

**Comment by joetsoi** [comment]
It defaults to true, so if you haven't set it then it should already be on

**Comment by thebigspoon** [comment]
yep, it's currently set to `false` in `production.ini`. Let's test this out after #50 is completed

**Comment by thebigspoon** [comment]
issue #90 weeded out most of the problems with turning this on. Fixed the tests and wrote new tests for create/update endpoints. Now it's time to have it on for good! Closing
