### ISSUE TITLE
Adding a new project should be a single page workflow

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#5]
When creating a new project, there is a still a dialog that asks users to upload resources/data.  When creating a new project, there should only be a single page which includes all of the fields.

<img width="944" alt="screen shot 2015-10-02 at 4 28 36 pm" src="https://cloud.githubusercontent.com/assets/10539483/10259914/ce58458a-6922-11e5-90f8-6814f0727990.png">

**Comment by joetsoi** [comment]
I will just remove resources entirely, I assume we no longer want images for projects?

**Comment by wonderchook** [comment]
@joetsoi no we need images for projects as well.

**Comment by galenerickson** [comment]
@joetsoi, as Kate says, please keep project image at the project attributes level.  This is a change from what was in the requirements doc that we sent over.  I'll make and update and send that back.
