### ISSUE TITLE
Create Project/Edit Project Details - ONA API Token field

### ISSUE THREAD

**Issue by danielduhh** [Cadasta/ckanext-project#55]
http://cadasta-staging.spatialdevmo.com/project/edit/haiti-assistance-program
http://cadasta-staging.spatialdevmo.com/project/new

Each project needs to be assigned an ONA API Token. Therefore, we need an ONA API Token text field on the CREATE & EDIT project page.

I've added ona_api_token to the create project /projects POST endpoint, as well as the edit project /projects/:id PATCH endpoint. 

The endpoint is looking for an object with an "ona_api_key" property

This updated endpoint has not been pushed to the staging API; however, it is on the dev branch of the cadasta-api. Let me know if you need more info or want me to push to staging..

**Comment by thebigspoon** [comment]
fixed and deployed to stagingd
