### ISSUE TITLE
GET or POST Endpoint?

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#60]
@sbindman and/or @danielduhh:

I see in these controllers we have some URLs hardcoded ( [project-parcel](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/project/public/project-dashboard/src/controllers/project-parcel.js#L357), [project-resources](https://github.com/Cadasta/ckanext-project/blob/dev/ckanext/project/public/project-dashboard/src/controllers/project-resources.js#L95) ). As far as I can tell they are URLs for the [getProjectParcelsResource Endpoint](http://54.69.121.180:3000/docs/#api-Projects-GetProjectParcelResources). 

But they also appear to be part of a `FileUploader`.  Are these future endpoints that we will `POST` to?

**Comment by danielduhh** [comment]
Those are not hardcoded; and we are POSTing to them. It's this endpoint: 54.69.121.180:3000/docs/#api-Resources-UploadResource

**Comment by thebigspoon** [comment]
word, i could not find that endpoint for the life me!
