### ISSUE TITLE
Can't see confirm button on 'Edit organization details'

### ISSUE THREAD

**Issue by devinercolano** [Cadasta/ckanext-project#63]
--reproduction steps--

-navigate to Organizations
- select an organization
- click the blue pencil on the right side of the screen

--expected result--
- save changes to the selected organization
![can tseeconfirmbuttonwell](https://cloud.githubusercontent.com/assets/4064770/10796252/aa973088-7d5a-11e5-9aab-2d05b91e7445.png)

--actual result--
- saved changes to organization

**Comment by thebigspoon** [comment]
fixed
