### ISSUE TITLE
Replace "delete" button with "archive" button on the edit Project/Org pages

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#64]
The edit pages for Organization and Project have a "delete" button.  The truth is that these projects don't get deleted, rather they are archived, and still the database.  We need to change the button and text and any associated messaging.

**Comment by galenerickson** [comment]
Looks like we aren't archiving or deleting for the MVP

**Comment by rgwozdz** [comment]
Ok, we need to hide the delete button,

On Oct 30, 2015, at 3:29 PM, galenerickson <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like we aren't archiving or deleting for the MVP

**Comment by thebigspoon** [comment]
fixed and deployed
