### ISSUE TITLE
Proper messaging on new Org/Project creation failure due to archived entity with same name.

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/ckanext-project#65]
If a user tries to create a new org or project and gives it a name of an archived entity, the messaging suggests the the name is already in use (which it is, but it is confusing because archived entity won't appear anywhere in the UI).  We need to adjust user messaging to explain that the name is attached to an archived project

**Comment by thebigspoon** [comment]
fixed and deployed to staging
