### ISSUE TITLE
Unique Constraint on project_ona_api_key_key and Error Response Format

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#68]
I'm trying to post an empty `ona_api_key` to [create project endpoint](http://54.69.121.180:3000/docs/#api-Projects-PostProjects) and might be seeing a couple issues with the response:

```bash
# REQUEST PARAMS
{
        "cadasta_organization_id": 1, 
        "description": "", 
        "title": "FakeProject2", 
        "ckan_id": "fakeproject2", 
        "ckan_name": "fakeproject2", 
        "ona_api_key": ""
    }
}

# RESPONSE
status=500
response={
    "error": "duplicate key value violates unique constraint \"project_ona_api_key_key\""
}
```
1. @danielduhh is the unique constraint supposed to be on that field? 

2. This endpoint I think used to return a hash with an error message. I'm not sure. Does cadasta have a standard error message format? My code was expecting the format below
```javascript
{ "message": "duplicate key value violates unique constraint \"project_ona_api_key_key"}
```

**Comment by thebigspoon** [comment]
thanks @danielduhh, I'll create another ticket for me on this one

**Comment by hallahan** [comment]
I would say that we should allow a project to not have an ona API key. Also, this key should not have to be unique. Remember that the Ona provider is just one way to slurp data.

We need logic where if the Ona API key is empty string or null to not set up triggers. We also need an API post endpoint where when an new key is posted, a new trigger should be set up

**Comment by danielduhh** [comment]
There is no null constraint on this field

**Comment by rgwozdz** [comment]
@danielduhh - thanks for clarifying that.  Here are some details:

1) The field doesn't have any NOT NULL contstraint.  
2) The field DOES have a UNIQUE constraint. @hallahan can u go into more detail as to why each project need not have a unique ONA API key? If they keys weren't unique to a projects, projects would/could share the same data?  I'd like to clarify this with Kate today if that is what you are thinking
3) The function to create a project does require the api-key argument, but it can have a value of NULL.
4) The API endpoint (Cadasta) currently requires an "ona-api-key" POST property, but its value can be NULL

**Comment by hallahan** [comment]
I'm trying to remember if Postgres allows null values with a unique constraint. I know that's DBMS specific. @shawnaparadee would know the answer.

Basically, we gotta have null. That's all that matters.

**Comment by hallahan** [comment]
I'm in agreement that there should be a unique Ona API key per project, but we dont have to make that a constraint in the DB itself. Should just be part of the app logic.

**Comment by thebigspoon** [comment]
works, but created #69
