### ISSUE TITLE
Feature Request: Add "Required Field" tag to required fields on New Org and New Project pages

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#7]
Currently I see a tag but it isn't in the correct place. It would be great to indicate which are the required fields. (see table below)

![screen shot 2015-10-05 at 3 17 57 pm](https://cloud.githubusercontent.com/assets/10539483/10295429/71222cb4-6b75-11e5-95b5-440505c0c0c0.png)

<img width="469" alt="screen shot 2015-10-05 at 3 15 39 pm" src="https://cloud.githubusercontent.com/assets/10539483/10295414/6cf82198-6b75-11e5-8eb6-2e78a1aa0b08.png">

**Comment by sbindman** [comment]
Still missing required fields on add project page.

**Comment by thebigspoon** [comment]
fixed and merged
