### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by galenerickson** [Cadasta/ckanext-project#70]
When I upload an image I get the missing media looking link.
![image](https://cloud.githubusercontent.com/assets/2992535/10859347/efcc4e52-7f19-11e5-82c0-229f7b2e8616.png)

Also, when I try to delete the image file from the project I get a  server error:
![image](https://cloud.githubusercontent.com/assets/2992535/10859378/265ae320-7f1a-11e5-86fc-6ab2b598954d.png)

**Comment by thebigspoon** [comment]
there was no code for this fix. let's just remember that the `production.ini` needs the correct storage setting and perms:
`ckan.storage_path = /var/lib/ckan/default/storage`
`chown -R www-data:www-data /var/lib/ckan/default`

see example of successful upload here:
http://cadasta-staging.spatialdevmo.com/organization/fakeorg100#/overview
