### ISSUE TITLE
Project > Detail > Resources: Delete Checkbox but no Way to Commit To It

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#75]
What we do here depends on our discussion of things not being deleted or archived anymore:

1. If we no longer need to delete/archive project resources then should we remove the Delete checkbox in the UI below
![project_resource_no_delete_ui](https://cloud.githubusercontent.com/assets/208859/10871920/4348b55c-80aa-11e5-80a4-f122189078df.png)

2. If we can still do this then we should have UI that let's us persist the delete

**Comment by danielduhh** [comment]
I agree. The functionally is intended to activate the delete label as a button upon checkbox selection; not sure if we'll end up implementing...

**Comment by sbindman** [comment]
I removed the checkbox
