### ISSUE TITLE
Feature Request: Adding an image to a new project

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#8]
Apologies for the miscommunication but we actually do want to associate an image with a project.  Is it possible to upload the image from the first page (similar to the "add organization" example below) rather than having it be a separate page?

![screen shot 2015-10-05 at 3 48 07 pm](https://cloud.githubusercontent.com/assets/10539483/10295893/c4ee4924-6b78-11e5-88ee-f10c705ce89c.png)

**Comment by thebigspoon** [comment]
deprioritized, closing
