### ISSUE TITLE
Remove out of the Box CKAN routes we no longer need

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#83]
CKAN routes: https://github.com/ngds/ckanext-ngds/wiki/Understanding-CKAN-Routes

Routes that seem to still be problems ---
http://localhost:5000/project/la-paz/map

http://localhost:5000/tag

http://localhost:5000/revision

http://localhost:5000/stats#most-create

**Comment by thebigspoon** [comment]
boomers! done and done
